version: '3'

services:
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        ports:
            - 8000:8000
        depends_on:
            - db 
    db:
        image: postgres
        restart: always
        environment:
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
          POSTGRES_DB: myproject
    volumes:
      - db_data:/var/lib/postgresql/data/
        
volumes:
    db_data: