# Generated by Django 4.1.5 on 2023-04-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='lastname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
